# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q lThM.q
#$ -l mres=384G,h_data=96G,h_vmem=96G,himem
#$ -cwd
#$ -j y
#$ -N neg_study_hyperopt_random_20_X100
#$ -o neg_study_hyperopt_random_20_X100.log
#$ -m bea
#$ -M vperezdiaz@cfa.harvard.edu
#
# ----------------Modules------------------------- #
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

module load tools/conda
start-conda
conda activate starsml
module load tools/python/use-multi-thread
python3 /scratch/public/sao/vdiaz/workspace/starsml/scripts/negative_sampling_study.py --experiment_name neg_study_hyperopt_random_20_X100

#
echo = `date` job $JOB_NAME done